# Generated by Django 5.2.4

from django.db import migrations, models
import django.utils.timezone
import datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30, unique=True, verbose_name='Firebase UID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('custom_username', models.CharField(blank=True, max_length=30, null=True, verbose_name='Custom Username')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(default='Bio')),
                ('about', models.TextField(blank=True, default='About')),
                ('date_of_birth', models.DateField(default=datetime.date(2025, 1, 1))),
                ('location', models.CharField(default='Nairobi', max_length=255)),
                ('platforms', models.JSONField(default=list)),
                ('games', models.JSONField(default=list)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gamer',
                'verbose_name_plural': 'Gamers',
            },
        ),
    ]
