# Generated by Django 5.2.4 on 2025-09-24 18:24

import datetime
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30, unique=True, verbose_name='Firebase UID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('custom_username', models.CharField(blank=True, max_length=30, null=True, verbose_name='Custom Username')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(default='Bio')),
                ('about', models.TextField(blank=True, default='About')),
                ('date_of_birth', models.DateField(default=datetime.date(2025, 1, 1))),
                ('location', models.CharField(default='', max_length=255)),
                ('platforms', models.JSONField(default=list)),
                ('games', models.JSONField(default=list)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0, help_text="User's total points earned from gaming activities")),
            ],
            options={
                'verbose_name': 'Gamer',
                'verbose_name_plural': 'Gamers',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('uid'), name='unique_lower_uid'), models.UniqueConstraint(models.F('email'), name='unique_email')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=64)),
                ('target_type', models.CharField(blank=True, max_length=32)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.gamer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
