# Generated by Django 5.1.3 on 2025-08-22 12:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('uid'), name='unique_lower_uid'),
        ),
        migrations.AddConstraint(
            model_name='gamer',
            constraint=models.UniqueConstraint(models.F('email'), name='unique_email'),
        ),
    ]
