# Generated by Django 5.2.4 on 2025-08-25 12:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='gamer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('uid'), name='unique_lower_uid'),
        ),
        migrations.AddConstraint(
            model_name='gamer',
            constraint=models.UniqueConstraint(models.F('email'), name='unique_email'),
        ),
    ]
