# Generated by Django 5.1.3 on 2025-08-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_handle_duplicates_and_add_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
