# Generated by Django 5.1.3 on 2025-08-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gamer_unique_lower_uid_gamer_unique_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
