# Generated by Django 5.1.3 on 2025-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_gamer_location_gamer_unique_lower_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text="User's total points earned from gaming activities"),
        ),
    ]
