# Generated by Django 5.2.4 on 2025-09-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='WHO WE ARE', max_length=100)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
                ('active_players', models.CharField(default='Active Players', max_length=50)),
                ('tournaments', models.CharField(default='Tournaments', max_length=50)),
                ('platforms', models.CharField(default='Platforms', max_length=50)),
                ('active_players_count', models.CharField(default='10K+', max_length=50)),
                ('tournaments_count', models.CharField(default='100+', max_length=50)),
                ('platforms_count', models.CharField(default='4', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(upload_to='sliders/')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
