# Generated by Django 5.2.4 on 2025-09-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('background_image', models.ImageField(upload_to='sliders/')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
