# Generated by Django 5.2.4 on 2025-09-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider_delete_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='about',
            name='active_players_count',
            field=models.CharField(default='10K+', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='badge_text',
            field=models.CharField(default='WHO WE ARE', max_length=100),
        ),
        migrations.AddField(
            model_name='about',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='about',
            name='platforms_count',
            field=models.CharField(default='4', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='tournaments_count',
            field=models.CharField(default='500+', max_length=50),
        ),
        migrations.AddField(
            model_name='platform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-star', max_length=50)),
                ('color', models.CharField(default='text-primary', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_cards', to='core.about')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
