# Generated by Django 5.2.4 on 2025-09-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_platform_options_alter_slider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='active_players',
            field=models.CharField(default='Active Players', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='platforms',
            field=models.CharField(default='Platforms', max_length=50),
        ),
        migrations.AddField(
            model_name='about',
            name='tournaments',
            field=models.CharField(default='Tournaments', max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='badge_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='tournaments_count',
            field=models.CharField(default='100+', max_length=50),
        ),
        migrations.DeleteModel(
            name='FeatureCard',
        ),
    ]
