# Generated by Django 5.2.4 on 2025-09-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about_active_players_about_platforms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='name',
            new_name='platform_name',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='link',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='logo',
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_about',
            field=models.TextField(default='Connect your Steam, Epic, and Battle.net accounts'),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_badge',
            field=models.CharField(default='OUR PLATFORMS', max_length=100),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_description',
            field=models.TextField(default='One account for all your gaming platforms'),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_member_count',
            field=models.CharField(default='10K+', max_length=50),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_members',
            field=models.CharField(default='Players', max_length=50),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_title',
            field=models.CharField(default='Play Anywhere, Connect Everywhere', max_length=100),
        ),
    ]
