# Generated by Django 5.2.4 on 2025-09-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_platform_platform_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type_name', models.CharField(max_length=100)),
                ('platform_about', models.TextField()),
                ('platform_members', models.CharField(max_length=50)),
                ('platform_member_count', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='platform',
            name='platform_about',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='platform_member_count',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='platform_members',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='platform_name',
        ),
    ]
