# Generated by Django 5.2.4 on 2025-09-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_platformtype_remove_platform_platform_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformtype',
            options={},
        ),
    ]
