# Generated by Django 5.2.4 on 2025-09-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_platformtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={},
        ),
        migrations.AlterModelOptions(
            name='platformtype',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='platform',
            name='order',
        ),
    ]
