# Generated by Django 5.2.4 on 2025-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_platform_options_alter_platformtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_badge',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_title',
            field=models.CharField(max_length=100),
        ),
    ]
