# Generated by Django 5.2.4 on 2025-09-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_platform_platform_badge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='PlatformType',
        ),
    ]
